export const targetChannels = {
  tulkarm: {
    active: false,
    channels: [
      { name: "tulkarmi1", area: "טולכרם" },
      { name: "tulkarmi", area: "טולכרם" },
      { name: "tulkrmeoon", area: "טולכרם" },
      { name: "noursams", area: "נור שמס" },
      { name: "Aueiwo", area: "מחנות טולכרם" },
      { name: "pz6_77", area: "טולכרם" },
      { name: "TulkaremNet", area: "טולכרם" },
      { name: "tulkarmalmhem", area: "מחנה טולכרם" },
      { name: "samsalmohaiam", area: "מחנה טולכרם" },
      { name: "Tulkarmzapcwu", area: "טולכרם" },
      { name: "rasedtuolkarm", area: "מחנה טולכרם" },
      { name: "farounnn", area: "פרון" },
      { name: "shwikahvolcano1", area: "שוויכה" },
      { name: "ahrartullkarm", area: "טולכרם" },
      { name: "a7rartullkarm", area: "טולכרם" },
      { name: "mokhayam_tulkarem", area: "מחנה טולכרם" },
      { name: "tulkarembaladna1", area: "טולכרם" },
      { name: "tulkarembaladna10", area: "טולכרם" },
      { name: "thnabah", area: "דנאבה" },
      { name: "tulkarmalrohm", area: "טולכרם" },
      { name: "tulkarmalroh", area: "טולכרם" },
      { name: "noorshms", area: "נור שמס" },
      { name: "noorshmss", area: "נור שמס" },
      { name: "nurshamstulkarem", area: "נור שמס" },
      { name: "rasdnourshams", area: "נור שמס" },
      { name: "alqodc", area: "טולכרם" },
      { name: "fhjhchhv", area: "טולכרם" },
      { name: "TulkaremAlsmood", area: "טולכרם" },
      { name: "ShababTulkarm3", area: "טולכרם" },
      { name: "monakshata7ramulkarem", area: "מחנה טולכרם" },
      { name: "tulkarem1", area: "מחנה טולכרם" },
      { name: "Ahssisn", area: "מחנות טולכרם" },
      { name: "abna2baqaalsharqia", area: "בקה אל-שרקיה" },
      { name: "asuatljbv", area: "מחנה טולכרם" },
      { name: "Tulkaremnews", area: "טולכרם" },
      { name: "tullkarm_green", area: "טולכרם" },
      { name: "shatha_sabagh", area: "טולכרם" },
      { name: "toulkarem", area: "טולכרם" },
      { name: "AMRBGT", area: "מחנות טולכרם" },
      { name: "ahdath_tulkarm", area: "מחנה טולכרם" },
      { name: "alredalsrey", area: "טולכרם" },
      { name: "norshames", area: "נור שמס" },
      { name: "shuhada_palestine_1", area: "קופין" },
      { name: "AhrarNoorShams", area: "נור שמס" },
      { name: "ahrartullkarm2", area: "טולכרם" },
      { name: "the_event1", area: "טולכרם" },
      { name: "mokem_tolkarmm", area: "מחנה טולכרם" },
      { name: "Karmool1", area: "טולכרם" },
    ],
  },
  yehuda: {
    active: true,
    channels: [
      { name: "HebMix", area: "חברון" },
      { name: "vipdahrya", area: "דאהריה" },
      { name: "khalelnews", area: "חלחול" },
      { name: "aroubcamb", area: "ערב אל-כמב" },
      { name: "aljanoop48", area: "אל-ג'נוב" },
      { name: "doura2000", area: "דורה" },
      { name: "DuraCity", area: "דורה" },
      { name: "From_hebron", area: "חברון" },
      { name: "al_fawwar", area: "אל-פוואר" },
      { name: "IdnaNews0", area: "עידנא" },
      { name: "dahraih", area: "דאהריה" },
      { name: "HebronNewss", area: "חברון" },
      { name: "alsamou_alhadth", area: "אל-סמוע" },
      { name: "From_hebron", area: "חברון" },
      { name: "saeare", area: "סעיר" },
    ],
  },
  etzion: {
    active: true,
    channels: [
      { name: "tuqualhadath", area: "תקוע" },
      { name: "Teqoua_Now", area: "תקוע" },
      { name: "BethlehemCommunityCh", area: "בית לחם" },
      { name: "bethlehemnewss", area: "בית לחם" },
      { name: "Aidacamp67", area: "בית לחם" },
      { name: "KutlaBU", area: "בית לחם" },
      { name: "bethlahemnow", area: "בית לחם" },
      { name: "dheisheh_event19486", area: "דהיישה" },
      { name: "dheisheh_Hadath", area: "דהיישה" },
      { name: "dheisheh_event48", area: "דהיישה" },
      { name: "dheisheh_event194867", area: "דהיישה" },
      { name: "beitommar9", area: "בית אומר" },
      { name: "Hebron_Beit_Ommer", area: "בית אומר" },
      { name: "beitommer", area: "בית אומר" },
      { name: "bietommar", area: "בית אומר" },
      { name: "sgfxxc", area: "נחלין" },
      { name: "marahrabahnow", area: "מראח רבאח" },
      { name: "ahrarsurif", area: "צוריף" },
      { name: "Aidacamp48", area: "מ.פ אל עיידה" },
      { name: "halhul2024", area: "חלחול" },
      { name: "alawaelnewsagancy", area: "עיזריה" },
      { name: "baninaeim22", area: "בני נעים" },
      { name: "saeare", area: "סעיר שיוח" },
      { name: "S3EERR", area: "סעיר שיוח" },
      { name: "Betfajaralhadth", area: "בית פגאר" },
      { name: "abo_dis", area: "אבו דיס" },
      { name: "osint941bot", area: "בדיקות" },
    ],
  },
  menashe: {
    active: false,
    channels: [],
  },
  binyamin: {
    active: false,
    channels: [],
  },
};

export const toggleGroup = (groupName, active) => {
  if (targetChannels[groupName]) {
    targetChannels[groupName].active = active;
    return true;
  }
  return false;
};

export const isGroupActive = (groupName) => {
  return targetChannels[groupName]?.active ?? false;
};
